'''
 Project: MPG Desktop Application
 Module:  database.py
 
 Description: 
 This module defines the database for the Gas Desktop Application.
The database schema is

Gas Fillup Entry 
   [0] RecordID: <<auto-generated>>
   [1] Date: yyyy/mm/dd
   [2] Gallons: xx.xxx
   [3] Mileage: xxxxx.x  (miles)
   [4] Price:   xx.xx   (US Dollars)
   [5] Station:  <<text>>
   [6] Notes:    <<text>> 
 
 Name          Date       Issue   
 R. Gaisey   11/01/23   initial commit
 R. Gaisey   11/18/23   file save function

 '''

import datetime
import xml.etree.ElementTree as ET
from enum import IntEnum


class EntryTags(IntEnum):
   RECORDID = 0
   DATE     = 1
   GALLONS  = 2
   MILEAGE  = 3
   PRICE    = 4
   STATION  = 5
   NOTES    = 6

class DataBase:
    def __init__(self, filename):
        self.filename = filename
        self.Entries = []
        self.backupFile = "liveBackup.xml"

        self.save_xml_to_list(filename)
        self.save_tree_to_file()
        #self.print_entries()


    def get_size (self):
        return  len(self.Entries) 
         

    def save_xml_to_list (self, xmlfile):

        self.tree = ET.parse(xmlfile) 

        # get root element 
        root = self.tree.getroot() 

        for child in root: 

            row  = []
            for elements in child:
                row.append(elements.text)
            self.Entries.append(row)


    def save_tree_to_file (self):
        self.tree.write(self.backupFile, encoding="utf-8")  


    def add_entry (self, date, gallons, mileage, cost, station, notes):
            
        newID = self.get_new_RecordID
        row  = [newID, date, gallons, mileage, cost, station, notes]
        self.Entries.append(row)


    def print_entries(self):
        # iterate news items 
        root = self.tree.getroot() 
        for child in root: 
            for elements in child:
                print (f' {elements.tag}: {elements.text} ')

            print('\n\n')


    def get_new_RecordID(self):
        root = self.tree.getroot() 

        maxRecordID = 0
        for entry in root.findall('row'):
           currID = int(entry.find('RecordID').text)
           if currID > maxRecordID: 
              maxRecordID = currID

        return (maxRecordID + 1)
    

    @staticmethod
    def get_date():
        return str(datetime.datetime.now()).split(" ")[0]


'''

if __name__=="__main__":
    db = DataBase("utilities/gas_raw.xml")
    db.print_entries()
        
'''